/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cetpro_Inicio.java
 *
 * Created on 21/11/2012, 04:22:35 PM
 */

package vista;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Rosy
 */

public class G_Inicio extends javax.swing.JFrame {
    private Timer timer;
    int cont;
    private String newline;
    public final static int ONE_SECOND = 1;

    /** Creates new form G_Inicio */

     public G_Inicio() {
        cont =-1;
        initComponents();
        jProgressBar1.setValue(0);
        jProgressBar1.setStringPainted(true);
        jbtn_logueo.setVisible(false);
        timer = new Timer(ONE_SECOND, new TimerListener());
        timer.start();
        setLocationRelativeTo(null);
    }

    private void abrirLogin() {
        Login single = Login.instancia();
            single.setVisible(true);
    }
    class TimerListener implements ActionListener {
          public void actionPerformed(ActionEvent evt) {
            cont++;
            jProgressBar1.setValue(cont);
            if(cont==2000){
                timer.stop();
                jbtn_logueo.setVisible(true);
                lblmensaje.setText("Listo!!");                 
            }
        }
     }

    public void esconder(){
        this.setVisible(false);
    }


    public void activar()
    {
        timer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jbtn_logueo = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema CETPRO Carabayllo");

        jPanel3.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));

        jProgressBar1.setMaximum(2000);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/recursos/logo.jpg"))); // NOI18N

        jbtn_logueo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_logueo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/recursos/buscar_icon.png"))); // NOI18N
        jbtn_logueo.setText("Logueo");
        jbtn_logueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_logueoActionPerformed(evt);
            }
        });

        lblmensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblmensaje.setForeground(new java.awt.Color(0, 0, 102));
        lblmensaje.setText("Iniciandose ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_logueo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblmensaje)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblmensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_logueo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_logueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_logueoActionPerformed
        esconder(); 
        abrirLogin();
    }//GEN-LAST:event_jbtn_logueoActionPerformed

    /**
    * @param args the command line arguments
    */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jbtn_logueo;
    private javax.swing.JLabel lblmensaje;
    // End of variables declaration//GEN-END:variables

}
